### ISSUE TITLE
Using the same wasm instance for one request

### ISSUE THREAD

**Issue by Taction** [http-wasm/http-wasm-host-go#68]
`handle_request` returns 32-bits of `ctx` which propagates to handle_response. Typical use is the correlation of request state.
For the current implementation, the wasm instance gets from the pool inside function `handleRequest` or `handleResponse`, so they are mostly different instance, if there are any values saved related to ctx value, the wasm application can not get it when `handleResponse` is called.

**Comment by codefromthecrypt** [comment]
you are absolutely right. fixing this now!

**Comment by codefromthecrypt** [comment]
https://github.com/http-wasm/http-wasm-host-go/pull/69
