### ISSUE TITLE
How to add new API functions?

### ISSUE THREAD

**Issue by springrain** [http-wasm/http-wasm-host-go#74]
Currently, there are api.HandleRequest and api.HandleResponse. I would like to add an API for data operations, such as adding, deleting, modifying, and querying databases. What should I do? Thank you very much for your guidance

**Comment by codefromthecrypt** [comment]
This is an HTTP based project, so it won't include features like querying databases. The only likely addition to this project would be outbound HTTP Client, as it was recently asked for.

So, questions about features out of the scope of this repository are better for chat. Can you try this slack room?
https://join.slack.com/t/newworkspace-6gk8596/shared_invite/zt-1rivu8e1g-qxn595SvkrbZBxvrA~aX1w
